# Generated by Django 3.1.2 on 2020-10-13 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('cargs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('description', models.TextField()),
                ('cargo', models.ManyToManyField(related_name='app_cargo', to='cargs.CargoModel')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_company', to='companies.companymodel')),
            ],
        ),
    ]
